const types = {
    FETCH_NOTIFICATION_START:"FETCH_NOTIFICATION_START",
    FETCH_NOTIFICATION_SUCCESS:"FETCH_NOTIFICATION_SUCCESS",
    FETCH_NOTIFICATION_FAILURE:"FETCH_NOTIFICATION_FAILURE",
    SEND_REQUEST_START:"SEND_REQUEST_START",
    SEND_REQUEST_SUCCESS:"SEND_REQUEST_SUCCESS",
    SEND_REQUEST_FAILURE:"SEND_REQUEST_FAILURE",
    RESET_ERROR:"RESET_ERROR",
    SET_CURRENT_NOTIFICATIONS:"SET_CURRENT_NOTIFICATIONS",
    REMOVE_NOTIFICATION_START:"REMOVE_NOTIFICATION_START",
    REMOVE_NOTIFICATION_SUCCESS:"REMOVE_NOTIFICATION_SUCCESS",
    REMOVE_NOTIFICATION_FAILURE:"REMOVE_NOTIFICATION_FAILURE",
    NOTIFY_FRIENDS_START:'NOTIFY_FRIENDS_START',
    NOTIFY_FRIENDS_SUCCESS:'NOTIFY_FRIENDS_SUCCESS',
    NOTIFY_FRIENDS_FAILURE:'NOTIFY_FRIENDS_FAILURE',
}
export default types