const types = {
    FETCH_NOTIFICATION_START:"FETCH_NOTIFICATION_START",
    FETCH_NOTIFICATION_SUCCESS:"FETCH_NOTIFICATION_SUCCESS",
    FETCH_NOTIFICATION_FAILURE:"FETCH_NOTIFICATION_FAILURE",
    SEND_REQUEST_START:"SEND_REQUEST_START",
    SEND_REQUEST_SUCCESS:"SEND_REQUEST_SUCCESS",
    SEND_REQUEST_FAILURE:"SEND_REQUEST_FAILURE",
    RESET_ERROR:"RESET_ERROR"
}
export default types