export const JournalsActionTypes = {
    SUBMIT_JOURNAL_SUCCESS:'SUBMIT_JOURNAL_SUCCESS',
    SUBMIT_JOURNAL_START:'SUBMIT_JOURNAL_START',
    SUBMIT_JOURNAL_FAILURE:'SUBMIT_JOURNAL_FAILURE',
    REMOVE_JOURNAL:'REMOVE_JOURNAL',
    EDIT_JOURNAL:'EDIT_JOURNAL',
    FETCH_JOURNALS:'FETCH_JOURNALS'
}