export const JournalsActionTypes = {
    SUBMIT_JOURNAL_SUCCESS:'SUBMIT_JOURNAL_SUCCESS',
    SUBMIT_JOURNAL_START:'SUBMIT_JOURNAL_START',
    SUBMIT_JOURNAL_FAILURE:'SUBMIT_JOURNAL_FAILURE',
    REMOVE_JOURNAL:'REMOVE_JOURNAL',
    EDIT_JOURNAL:'EDIT_JOURNAL',
    FETCH_JOURNALS_START:'FETCH_JOURNALS_START',
    FETCH_JOURNALS_SUCCESS:'FETCH_JOURNALS_SUCCESS',
    FETCH_JOURNALS_FAILURE:'FETCH_JOURNALS_FAILURE',
    SET_FIELD_VALUE:'SET_FIELD_VALUE'

}