const types = {
    SIGN_IN_START:'SIGN_IN_START',
    SIGN_IN_SUCCESS:'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE:'SIGN_IN_FAILURE',
    SIGN_OUT_START:'SIGN_OUT_START',
    SIGN_OUT_SUCCESS:'SIGN_OUT_SUCCESS',
    SIGN_OUT_FAILURE:'SIGN_OUT_FAILURE',
    ADD_TEAMMATE_START:'ADD_TEAMMATE_START',
    ADD_TEAMMATE_SUCCESS:"ADD_TEAMMATE_SUCCESS",
    ADD_TEAMMATE_FAILURE:'ADD_TEAMMATE_FAILURE',
    REMOVE_TEAMMATE_START:'REMOVE_TEAMMATE_START',
    REMOVE_TEAMMATE_SUCCESS:"REMOVE_TEAMMATE_SUCCESS",
    REMOVE_TEAMMATE_FAILURE:'REMOVE_TEAMMATE_FAILURE',

}
export default types